language: android

android:
  components:
    - platform-tools
    - tools
    - android-28
    - build-tools-28.0.3
    - extra-android-m2repository

before_script:
  - chmod +x gradlew
    
script:
  - "./gradlew build"

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/
cache:
  directories:
    - $HOME/.gradle